name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # Executa quando há mudanças na branch principal

permissions:
  contents: write  # Permissão para escrever conteúdo
  pages: write     # Permissão para escrever na branch do GitHub Pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Criar artefato para deploy
        uses: actions/upload-pages-artifact@v1  # Tente v1 se v2 não funcionar
        with:
          path: .  # Publica todos os arquivos do repositório

      - name: Publicar no GitHub Pages
        uses: actions/deploy-pages@v1
